### ISSUE TITLE
EOL pageid

### ISSUE THREAD

**Issue by maelle** [ropensci/traits#109]
How does one get it?

**Comment by sckott** [comment]
oof, EOL is kind of weird setup in my opinion. So species in EOL have page ids instead of taxon IDs, though I guess they're just different names. Can get one like 

```r
x = get_eolid('Quercus lobata', rows = 1)
attr(x, "uri")
#> [1] "http://eol.org/pages/1151479/overview"
stringr::str_extract(attr(x, "uri"), "[0-9]+")
#> [1] "1151479"
```

the ID you get from `get_eolid` is the taxon id, but the page id is in the `uri` attribute, so we can extract that page id. I opened an issue in taxize to put page id as a separate attribute so it can be extracted easier: https://github.com/ropensci/taxize/issues/702

**Comment by maelle** [comment]
Thanks!

**Comment by sckott** [comment]
no longer needed here since EOL Traitbank has changed their search interface
